/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auditoria/{tipoEntidade}/{entidadeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tipoEntidade: string;
                    entidadeId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuditoriaOperacaoDtoIReadOnlyListApiResponse"];
                        "application/json": components["schemas"]["AuditoriaOperacaoDtoIReadOnlyListApiResponse"];
                        "text/json": components["schemas"]["AuditoriaOperacaoDtoIReadOnlyListApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditoria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    usuarioId?: number;
                    tipoEntidade?: string;
                    operacao?: string;
                    de?: string;
                    ate?: string;
                    pagina?: number;
                    porPagina?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuditoriaOperacaoDtoResultadoPaginadoDto"];
                        "application/json": components["schemas"]["AuditoriaOperacaoDtoResultadoPaginadoDto"];
                        "text/json": components["schemas"]["AuditoriaOperacaoDtoResultadoPaginadoDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginDto"];
                    "text/json": components["schemas"]["LoginDto"];
                    "application/*+json": components["schemas"]["LoginDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResultDtoApiResponse"];
                        "application/json": components["schemas"]["LoginResultDtoApiResponse"];
                        "text/json": components["schemas"]["LoginResultDtoApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UsuarioDtoApiResponse"];
                        "application/json": components["schemas"]["UsuarioDtoApiResponse"];
                        "text/json": components["schemas"]["UsuarioDtoApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UsuarioDtoIReadOnlyListApiResponse"];
                        "application/json": components["schemas"]["UsuarioDtoIReadOnlyListApiResponse"];
                        "text/json": components["schemas"]["UsuarioDtoIReadOnlyListApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CriarUsuarioDto"];
                    "text/json": components["schemas"]["CriarUsuarioDto"];
                    "application/*+json": components["schemas"]["CriarUsuarioDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CriadoDtoApiResponse"];
                        "application/json": components["schemas"]["CriadoDtoApiResponse"];
                        "text/json": components["schemas"]["CriadoDtoApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/usuarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AtualizarUsuarioDto"];
                    "text/json": components["schemas"]["AtualizarUsuarioDto"];
                    "application/*+json": components["schemas"]["AtualizarUsuarioDto"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/usuarios/{id}/permissao-auditoria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AtualizarPermissaoAuditoriaDto"];
                    "text/json": components["schemas"]["AtualizarPermissaoAuditoriaDto"];
                    "application/*+json": components["schemas"]["AtualizarPermissaoAuditoriaDto"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    filtro?: string;
                    pagina?: number;
                    porPagina?: number;
                    incluirInativos?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ClienteDtoResultadoPaginadoDto"];
                        "application/json": components["schemas"]["ClienteDtoResultadoPaginadoDto"];
                        "text/json": components["schemas"]["ClienteDtoResultadoPaginadoDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CriarClienteCommand"];
                    "text/json": components["schemas"]["CriarClienteCommand"];
                    "application/*+json": components["schemas"]["CriarClienteCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CriadoDtoApiResponse"];
                        "application/json": components["schemas"]["CriadoDtoApiResponse"];
                        "text/json": components["schemas"]["CriadoDtoApiResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clientes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ClienteDtoApiResponse"];
                        "application/json": components["schemas"]["ClienteDtoApiResponse"];
                        "text/json": components["schemas"]["ClienteDtoApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AtualizarClienteCommand"];
                    "text/json": components["schemas"]["AtualizarClienteCommand"];
                    "application/*+json": components["schemas"]["AtualizarClienteCommand"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clientes/{id}/ordens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrdemServicoResumoDtoIReadOnlyListApiResponse"];
                        "application/json": components["schemas"]["OrdemServicoResumoDtoIReadOnlyListApiResponse"];
                        "text/json": components["schemas"]["OrdemServicoResumoDtoIReadOnlyListApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cobrancas/historico": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    ordemServicoId?: number;
                    somenteFalhas?: boolean;
                    pagina?: number;
                    porPagina?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HistoricoCobrancaDtoResultadoPaginadoDto"];
                        "application/json": components["schemas"]["HistoricoCobrancaDtoResultadoPaginadoDto"];
                        "text/json": components["schemas"]["HistoricoCobrancaDtoResultadoPaginadoDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cobrancas/disparar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CobrancaJobResultadoApiResponse"];
                        "application/json": components["schemas"]["CobrancaJobResultadoApiResponse"];
                        "text/json": components["schemas"]["CobrancaJobResultadoApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cobrancas/disparar/{ordemServicoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ordemServicoId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CobrancaIndividualResultadoApiResponse"];
                        "application/json": components["schemas"]["CobrancaIndividualResultadoApiResponse"];
                        "text/json": components["schemas"]["CobrancaIndividualResultadoApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configuracoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ConfiguracaoDtoListApiResponse"];
                        "application/json": components["schemas"]["ConfiguracaoDtoListApiResponse"];
                        "text/json": components["schemas"]["ConfiguracaoDtoListApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configuracoes/{chave}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chave: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ConfiguracaoDtoApiResponse"];
                        "application/json": components["schemas"]["ConfiguracaoDtoApiResponse"];
                        "text/json": components["schemas"]["ConfiguracaoDtoApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chave: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AtualizarConfiguracaoBody"];
                    "text/json": components["schemas"]["AtualizarConfiguracaoBody"];
                    "application/*+json": components["schemas"]["AtualizarConfiguracaoBody"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["StatusOrdem"];
                    clienteId?: number;
                    abertaDe?: string;
                    abertaAte?: string;
                    pagina?: number;
                    porPagina?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrdemServicoResumoDtoResultadoPaginadoDto"];
                        "application/json": components["schemas"]["OrdemServicoResumoDtoResultadoPaginadoDto"];
                        "text/json": components["schemas"]["OrdemServicoResumoDtoResultadoPaginadoDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AbrirOrdemServicoCommand"];
                    "text/json": components["schemas"]["AbrirOrdemServicoCommand"];
                    "application/*+json": components["schemas"]["AbrirOrdemServicoCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CriadoDtoApiResponse"];
                        "application/json": components["schemas"]["CriadoDtoApiResponse"];
                        "text/json": components["schemas"]["CriadoDtoApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrdemServicoDetalheDtoApiResponse"];
                        "application/json": components["schemas"]["OrdemServicoDetalheDtoApiResponse"];
                        "text/json": components["schemas"]["OrdemServicoDetalheDtoApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AtualizarOrdemServicoCommand"];
                    "text/json": components["schemas"]["AtualizarOrdemServicoCommand"];
                    "application/*+json": components["schemas"]["AtualizarOrdemServicoCommand"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens/{id}/servicos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AdicionarItemServicoBody"];
                    "text/json": components["schemas"]["AdicionarItemServicoBody"];
                    "application/*+json": components["schemas"]["AdicionarItemServicoBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CriadoDtoApiResponse"];
                        "application/json": components["schemas"]["CriadoDtoApiResponse"];
                        "text/json": components["schemas"]["CriadoDtoApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens/{id}/servicos/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens/{id}/produtos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AdicionarItemProdutoBody"];
                    "text/json": components["schemas"]["AdicionarItemProdutoBody"];
                    "application/*+json": components["schemas"]["AdicionarItemProdutoBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CriadoDtoApiResponse"];
                        "application/json": components["schemas"]["CriadoDtoApiResponse"];
                        "text/json": components["schemas"]["CriadoDtoApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens/{id}/produtos/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens/{id}/fechar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens/{id}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pagamentos/pendencias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    somenteVencidas?: boolean;
                    pagina?: number;
                    porPagina?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrdemPendenteDtoResultadoPaginadoDto"];
                        "application/json": components["schemas"]["OrdemPendenteDtoResultadoPaginadoDto"];
                        "text/json": components["schemas"]["OrdemPendenteDtoResultadoPaginadoDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pagamentos/ordem/{ordemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ordemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagamentoDtoListApiResponse"];
                        "application/json": components["schemas"]["PagamentoDtoListApiResponse"];
                        "text/json": components["schemas"]["PagamentoDtoListApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pagamentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegistrarPagamentoCommand"];
                    "text/json": components["schemas"]["RegistrarPagamentoCommand"];
                    "application/*+json": components["schemas"]["RegistrarPagamentoCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CriadoDtoApiResponse"];
                        "application/json": components["schemas"]["CriadoDtoApiResponse"];
                        "text/json": components["schemas"]["CriadoDtoApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pagamentos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/produtos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    filtro?: string;
                    pagina?: number;
                    porPagina?: number;
                    incluirInativos?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProdutoDtoResultadoPaginadoDto"];
                        "application/json": components["schemas"]["ProdutoDtoResultadoPaginadoDto"];
                        "text/json": components["schemas"]["ProdutoDtoResultadoPaginadoDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CriarProdutoCommand"];
                    "text/json": components["schemas"]["CriarProdutoCommand"];
                    "application/*+json": components["schemas"]["CriarProdutoCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CriadoDtoApiResponse"];
                        "application/json": components["schemas"]["CriadoDtoApiResponse"];
                        "text/json": components["schemas"]["CriadoDtoApiResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/produtos/abaixo-minimo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProdutoDtoIReadOnlyListApiResponse"];
                        "application/json": components["schemas"]["ProdutoDtoIReadOnlyListApiResponse"];
                        "text/json": components["schemas"]["ProdutoDtoIReadOnlyListApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/produtos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProdutoDtoApiResponse"];
                        "application/json": components["schemas"]["ProdutoDtoApiResponse"];
                        "text/json": components["schemas"]["ProdutoDtoApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AtualizarProdutoCommand"];
                    "text/json": components["schemas"]["AtualizarProdutoCommand"];
                    "application/*+json": components["schemas"]["AtualizarProdutoCommand"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/produtos/{id}/estoque": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AjustarEstoqueBody"];
                    "text/json": components["schemas"]["AjustarEstoqueBody"];
                    "application/*+json": components["schemas"]["AjustarEstoqueBody"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/servicos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    incluirInativos?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CatalogoServicoDtoIReadOnlyListApiResponse"];
                        "application/json": components["schemas"]["CatalogoServicoDtoIReadOnlyListApiResponse"];
                        "text/json": components["schemas"]["CatalogoServicoDtoIReadOnlyListApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CriarCatalogoServicoCommand"];
                    "text/json": components["schemas"]["CriarCatalogoServicoCommand"];
                    "application/*+json": components["schemas"]["CriarCatalogoServicoCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CriadoDtoApiResponse"];
                        "application/json": components["schemas"]["CriadoDtoApiResponse"];
                        "text/json": components["schemas"]["CriadoDtoApiResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servicos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AtualizarCatalogoServicoCommand"];
                    "text/json": components["schemas"]["AtualizarCatalogoServicoCommand"];
                    "application/*+json": components["schemas"]["AtualizarCatalogoServicoCommand"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servicos/{id}/preco": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AtualizarPrecoBody"];
                    "text/json": components["schemas"]["AtualizarPrecoBody"];
                    "application/*+json": components["schemas"]["AtualizarPrecoBody"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiErrorResponse"];
                        "application/json": components["schemas"]["ApiErrorResponse"];
                        "text/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiValidationErrorResponse"];
                        "application/json": components["schemas"]["ApiValidationErrorResponse"];
                        "text/json": components["schemas"]["ApiValidationErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AbrirOrdemServicoCommand: {
            /** Format: int64 */
            clienteId?: number;
            descricaoProblema?: string | null;
            observacoes?: string | null;
        };
        AdicionarItemProdutoBody: {
            /** Format: int64 */
            produtoId?: number | null;
            nomeProduto?: string | null;
            /** Format: double */
            precoUnitario?: number | null;
            /** Format: int32 */
            quantidade?: number;
            produtoFornecidoPeloCliente?: boolean;
        };
        AdicionarItemServicoBody: {
            /** Format: int64 */
            catalogoServicoId?: number;
            /** Format: int32 */
            quantidade?: number;
        };
        AjustarEstoqueBody: {
            /** Format: int32 */
            quantidade?: number;
        };
        ApiErrorResponse: {
            erro?: string | null;
        };
        ApiValidationErrorResponse: {
            erro?: string | null;
            detalhes?: string[] | null;
        };
        AtualizarCatalogoServicoCommand: {
            /** Format: int64 */
            id?: number;
            nome?: string | null;
            descricao?: string | null;
            /** Format: double */
            preco?: number;
            ehMaoDeObraPadrao?: boolean;
        };
        AtualizarClienteCommand: {
            /** Format: int64 */
            id?: number;
            nome?: string | null;
            telefone?: string | null;
            email?: string | null;
            cpfCnpj?: string | null;
            endereco?: string | null;
            observacoes?: string | null;
        };
        AtualizarConfiguracaoBody: {
            valor?: string | null;
        };
        AtualizarOrdemServicoCommand: {
            /** Format: int64 */
            id?: number;
            descricaoProblema?: string | null;
            observacoes?: string | null;
            status?: components["schemas"]["StatusOrdem"];
        };
        AtualizarPermissaoAuditoriaDto: {
            podeVerAuditoria?: boolean;
        };
        AtualizarPrecoBody: {
            /** Format: double */
            preco?: number;
        };
        AtualizarProdutoCommand: {
            /** Format: int64 */
            id?: number;
            nome?: string | null;
            referencia?: string | null;
            /** Format: double */
            precoCusto?: number;
            /** Format: double */
            precoVenda?: number;
            /** Format: int32 */
            estoqueMinimo?: number;
        };
        AtualizarUsuarioDto: {
            nomeCompleto?: string | null;
            novaSenha?: string | null;
            ativo?: boolean;
        };
        AuditoriaOperacaoDto: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            ocorridoEm?: string;
            tipoEntidade?: string | null;
            /** Format: int64 */
            entidadeId?: number;
            operacao?: string | null;
            descricao?: string | null;
            /** Format: int64 */
            usuarioId?: number | null;
            usuarioNome?: string | null;
        };
        AuditoriaOperacaoDtoIReadOnlyListApiResponse: {
            dados?: components["schemas"]["AuditoriaOperacaoDto"][] | null;
        };
        AuditoriaOperacaoDtoResultadoPaginadoDto: {
            dados?: components["schemas"]["AuditoriaOperacaoDto"][] | null;
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            pagina?: number;
            /** Format: int32 */
            porPagina?: number;
        };
        CatalogoServicoDto: {
            /** Format: int64 */
            id?: number;
            nome?: string | null;
            descricao?: string | null;
            /** Format: double */
            preco?: number;
            ehMaoDeObraPadrao?: boolean;
            ativo?: boolean;
            /** Format: date-time */
            criadoEm?: string;
            /** Format: int64 */
            criadoPorUsuarioId?: number | null;
            criadoPorUsuarioNome?: string | null;
            /** Format: date-time */
            atualizadoEm?: string | null;
            /** Format: int64 */
            atualizadoPorUsuarioId?: number | null;
            atualizadoPorUsuarioNome?: string | null;
        };
        CatalogoServicoDtoIReadOnlyListApiResponse: {
            dados?: components["schemas"]["CatalogoServicoDto"][] | null;
        };
        ClienteDto: {
            /** Format: int64 */
            id?: number;
            nome?: string | null;
            telefone?: string | null;
            email?: string | null;
            cpfCnpj?: string | null;
            endereco?: string | null;
            observacoes?: string | null;
            /** Format: date-time */
            criadoEm?: string;
            ativo?: boolean;
            /** Format: int64 */
            criadoPorUsuarioId?: number | null;
            criadoPorUsuarioNome?: string | null;
            /** Format: date-time */
            atualizadoEm?: string | null;
            /** Format: int64 */
            atualizadoPorUsuarioId?: number | null;
            atualizadoPorUsuarioNome?: string | null;
        };
        ClienteDtoApiResponse: {
            dados?: components["schemas"]["ClienteDto"];
        };
        ClienteDtoResultadoPaginadoDto: {
            dados?: components["schemas"]["ClienteDto"][] | null;
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            pagina?: number;
            /** Format: int32 */
            porPagina?: number;
        };
        CobrancaIndividualResultado: {
            status?: string | null;
            mensagem?: string | null;
            erroEnvio?: string | null;
        };
        CobrancaIndividualResultadoApiResponse: {
            dados?: components["schemas"]["CobrancaIndividualResultado"];
        };
        CobrancaJobResultado: {
            /** Format: int32 */
            ordensVerificadas?: number;
            /** Format: int32 */
            enviadas?: number;
            /** Format: int32 */
            falhas?: number;
            /** Format: int32 */
            ignoradas?: number;
        };
        CobrancaJobResultadoApiResponse: {
            dados?: components["schemas"]["CobrancaJobResultado"];
        };
        ConfiguracaoDto: {
            chave?: string | null;
            valor?: string | null;
            descricao?: string | null;
            /** Format: date-time */
            criadoEm?: string;
            /** Format: int64 */
            criadoPorUsuarioId?: number | null;
            criadoPorUsuarioNome?: string | null;
            /** Format: date-time */
            atualizadoEm?: string | null;
            /** Format: int64 */
            atualizadoPorUsuarioId?: number | null;
            atualizadoPorUsuarioNome?: string | null;
        };
        ConfiguracaoDtoApiResponse: {
            dados?: components["schemas"]["ConfiguracaoDto"];
        };
        ConfiguracaoDtoListApiResponse: {
            dados?: components["schemas"]["ConfiguracaoDto"][] | null;
        };
        CriadoDto: {
            /** Format: int64 */
            id?: number;
        };
        CriadoDtoApiResponse: {
            dados?: components["schemas"]["CriadoDto"];
        };
        CriarCatalogoServicoCommand: {
            nome?: string | null;
            descricao?: string | null;
            /** Format: double */
            preco?: number;
            ehMaoDeObraPadrao?: boolean;
        };
        CriarClienteCommand: {
            nome?: string | null;
            telefone?: string | null;
            email?: string | null;
            cpfCnpj?: string | null;
            endereco?: string | null;
            observacoes?: string | null;
        };
        CriarProdutoCommand: {
            nome?: string | null;
            referencia?: string | null;
            /** Format: double */
            precoCusto?: number;
            /** Format: double */
            precoVenda?: number;
            /** Format: int32 */
            quantidadeEstoque?: number;
            /** Format: int32 */
            estoqueMinimo?: number;
        };
        CriarUsuarioDto: {
            nomeCompleto?: string | null;
            email?: string | null;
            senha?: string | null;
            role?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        FormaPagamento: 1 | 2 | 3 | 4;
        HistoricoCobrancaDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            ordemServicoId?: number;
            ordemNumero?: string | null;
            telefoneDestino?: string | null;
            /** Format: date-time */
            enviadoEm?: string;
            sucesso?: boolean;
            erroMensagem?: string | null;
            /** Format: int64 */
            criadoPorUsuarioId?: number | null;
            criadoPorUsuarioNome?: string | null;
        };
        HistoricoCobrancaDtoResultadoPaginadoDto: {
            dados?: components["schemas"]["HistoricoCobrancaDto"][] | null;
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            pagina?: number;
            /** Format: int32 */
            porPagina?: number;
        };
        ItemProdutoDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            produtoId?: number | null;
            nomeProduto?: string | null;
            /** Format: double */
            precoUnitario?: number;
            /** Format: int32 */
            quantidade?: number;
            produtoFornecidoPeloCliente?: boolean;
            /** Format: double */
            subtotal?: number;
        };
        ItemServicoDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            catalogoServicoId?: number;
            nomeServico?: string | null;
            /** Format: double */
            precoUnitario?: number;
            /** Format: int32 */
            quantidade?: number;
            /** Format: double */
            subtotal?: number;
        };
        LoginDto: {
            email?: string | null;
            senha?: string | null;
        };
        LoginResultDto: {
            token?: string | null;
            email?: string | null;
            nomeCompleto?: string | null;
            role?: string | null;
            /** Format: date-time */
            expiraEm?: string;
        };
        LoginResultDtoApiResponse: {
            dados?: components["schemas"]["LoginResultDto"];
        };
        OrdemPendenteDto: {
            /** Format: int64 */
            ordemServicoId?: number;
            numero?: string | null;
            /** Format: int64 */
            clienteId?: number;
            clienteNome?: string | null;
            clienteTelefone?: string | null;
            /** Format: date-time */
            fechadaEm?: string | null;
            /** Format: date-time */
            dataVencimentoPagamento?: string | null;
            /** Format: double */
            totalGeral?: number;
            /** Format: double */
            totalPago?: number;
            /** Format: double */
            saldoDevedor?: number;
            vencida?: boolean;
        };
        OrdemPendenteDtoResultadoPaginadoDto: {
            dados?: components["schemas"]["OrdemPendenteDto"][] | null;
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            pagina?: number;
            /** Format: int32 */
            porPagina?: number;
        };
        OrdemServicoDetalheDto: {
            /** Format: int64 */
            id?: number;
            numero?: string | null;
            /** Format: int64 */
            clienteId?: number;
            clienteNome?: string | null;
            descricaoProblema?: string | null;
            observacoes?: string | null;
            status?: components["schemas"]["StatusOrdem"];
            /** Format: date-time */
            abertaEm?: string;
            /** Format: date-time */
            fechadaEm?: string | null;
            /** Format: date-time */
            dataVencimentoPagamento?: string | null;
            servicos?: components["schemas"]["ItemServicoDto"][] | null;
            produtos?: components["schemas"]["ItemProdutoDto"][] | null;
            /** Format: double */
            totalServicos?: number;
            /** Format: double */
            totalProdutos?: number;
            /** Format: double */
            totalGeral?: number;
            /** Format: double */
            totalPago?: number;
            /** Format: double */
            saldoDevedor?: number;
            /** Format: int64 */
            criadoPorUsuarioId?: number | null;
            criadoPorUsuarioNome?: string | null;
            /** Format: date-time */
            atualizadoEm?: string | null;
            /** Format: int64 */
            atualizadoPorUsuarioId?: number | null;
            atualizadoPorUsuarioNome?: string | null;
        };
        OrdemServicoDetalheDtoApiResponse: {
            dados?: components["schemas"]["OrdemServicoDetalheDto"];
        };
        OrdemServicoResumoDto: {
            /** Format: int64 */
            id?: number;
            numero?: string | null;
            /** Format: int64 */
            clienteId?: number;
            clienteNome?: string | null;
            status?: components["schemas"]["StatusOrdem"];
            /** Format: date-time */
            abertaEm?: string;
            /** Format: date-time */
            fechadaEm?: string | null;
            /** Format: date-time */
            dataVencimentoPagamento?: string | null;
            /** Format: double */
            totalGeral?: number;
            /** Format: double */
            saldoDevedor?: number;
        };
        OrdemServicoResumoDtoIReadOnlyListApiResponse: {
            dados?: components["schemas"]["OrdemServicoResumoDto"][] | null;
        };
        OrdemServicoResumoDtoResultadoPaginadoDto: {
            dados?: components["schemas"]["OrdemServicoResumoDto"][] | null;
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            pagina?: number;
            /** Format: int32 */
            porPagina?: number;
        };
        PagamentoDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            ordemServicoId?: number;
            /** Format: double */
            valor?: number;
            forma?: components["schemas"]["FormaPagamento"];
            /** Format: date-time */
            pagoEm?: string;
            observacao?: string | null;
            /** Format: int64 */
            criadoPorUsuarioId?: number | null;
            criadoPorUsuarioNome?: string | null;
        };
        PagamentoDtoListApiResponse: {
            dados?: components["schemas"]["PagamentoDto"][] | null;
        };
        ProdutoDto: {
            /** Format: int64 */
            id?: number;
            nome?: string | null;
            referencia?: string | null;
            /** Format: double */
            precoCusto?: number;
            /** Format: double */
            precoVenda?: number;
            /** Format: int32 */
            quantidadeEstoque?: number;
            /** Format: int32 */
            estoqueMinimo?: number;
            ativo?: boolean;
            /** Format: date-time */
            criadoEm?: string;
            /** Format: int64 */
            criadoPorUsuarioId?: number | null;
            criadoPorUsuarioNome?: string | null;
            /** Format: date-time */
            atualizadoEm?: string | null;
            /** Format: int64 */
            atualizadoPorUsuarioId?: number | null;
            atualizadoPorUsuarioNome?: string | null;
        };
        ProdutoDtoApiResponse: {
            dados?: components["schemas"]["ProdutoDto"];
        };
        ProdutoDtoIReadOnlyListApiResponse: {
            dados?: components["schemas"]["ProdutoDto"][] | null;
        };
        ProdutoDtoResultadoPaginadoDto: {
            dados?: components["schemas"]["ProdutoDto"][] | null;
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            pagina?: number;
            /** Format: int32 */
            porPagina?: number;
        };
        RegistrarPagamentoCommand: {
            /** Format: int64 */
            ordemServicoId?: number;
            /** Format: double */
            valor?: number;
            forma?: components["schemas"]["FormaPagamento"];
            observacao?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        StatusOrdem: 1 | 2 | 3 | 4 | 5;
        UsuarioDto: {
            /** Format: int64 */
            id?: number;
            nomeCompleto?: string | null;
            email?: string | null;
            role?: string | null;
            ativo?: boolean;
            podeVerAuditoria?: boolean;
        };
        UsuarioDtoApiResponse: {
            dados?: components["schemas"]["UsuarioDto"];
        };
        UsuarioDtoIReadOnlyListApiResponse: {
            dados?: components["schemas"]["UsuarioDto"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
